# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18IfXReWTAVe_BaauA80tJjmQdTXNJ3l3
"""

score=input().split()
count=0
for i in len(score):
  if score[i]<60:
    count=count+1
print(count)